// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcpgate.proto

package iproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type GwError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwError) Reset()         { *m = GwError{} }
func (m *GwError) String() string { return proto.CompactTextString(m) }
func (*GwError) ProtoMessage()    {}
func (*GwError) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{0}
}

func (m *GwError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwError.Unmarshal(m, b)
}
func (m *GwError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwError.Marshal(b, m, deterministic)
}
func (m *GwError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwError.Merge(m, src)
}
func (m *GwError) XXX_Size() int {
	return xxx_messageInfo_GwError.Size(m)
}
func (m *GwError) XXX_DiscardUnknown() {
	xxx_messageInfo_GwError.DiscardUnknown(m)
}

var xxx_messageInfo_GwError proto.InternalMessageInfo

func (m *GwError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GwError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Method1Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method1Request) Reset()         { *m = Method1Request{} }
func (m *Method1Request) String() string { return proto.CompactTextString(m) }
func (*Method1Request) ProtoMessage()    {}
func (*Method1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{1}
}

func (m *Method1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method1Request.Unmarshal(m, b)
}
func (m *Method1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method1Request.Marshal(b, m, deterministic)
}
func (m *Method1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method1Request.Merge(m, src)
}
func (m *Method1Request) XXX_Size() int {
	return xxx_messageInfo_Method1Request.Size(m)
}
func (m *Method1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Method1Request.DiscardUnknown(m)
}

var xxx_messageInfo_Method1Request proto.InternalMessageInfo

type Method1Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method1Reply) Reset()         { *m = Method1Reply{} }
func (m *Method1Reply) String() string { return proto.CompactTextString(m) }
func (*Method1Reply) ProtoMessage()    {}
func (*Method1Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{2}
}

func (m *Method1Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method1Reply.Unmarshal(m, b)
}
func (m *Method1Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method1Reply.Marshal(b, m, deterministic)
}
func (m *Method1Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method1Reply.Merge(m, src)
}
func (m *Method1Reply) XXX_Size() int {
	return xxx_messageInfo_Method1Reply.Size(m)
}
func (m *Method1Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Method1Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Method1Reply proto.InternalMessageInfo

type Method2Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method2Request) Reset()         { *m = Method2Request{} }
func (m *Method2Request) String() string { return proto.CompactTextString(m) }
func (*Method2Request) ProtoMessage()    {}
func (*Method2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{3}
}

func (m *Method2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method2Request.Unmarshal(m, b)
}
func (m *Method2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method2Request.Marshal(b, m, deterministic)
}
func (m *Method2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method2Request.Merge(m, src)
}
func (m *Method2Request) XXX_Size() int {
	return xxx_messageInfo_Method2Request.Size(m)
}
func (m *Method2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Method2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Method2Request proto.InternalMessageInfo

type Method2Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method2Reply) Reset()         { *m = Method2Reply{} }
func (m *Method2Reply) String() string { return proto.CompactTextString(m) }
func (*Method2Reply) ProtoMessage()    {}
func (*Method2Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{4}
}

func (m *Method2Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method2Reply.Unmarshal(m, b)
}
func (m *Method2Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method2Reply.Marshal(b, m, deterministic)
}
func (m *Method2Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method2Reply.Merge(m, src)
}
func (m *Method2Reply) XXX_Size() int {
	return xxx_messageInfo_Method2Reply.Size(m)
}
func (m *Method2Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Method2Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Method2Reply proto.InternalMessageInfo

type MsgNotify struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNotify) Reset()         { *m = MsgNotify{} }
func (m *MsgNotify) String() string { return proto.CompactTextString(m) }
func (*MsgNotify) ProtoMessage()    {}
func (*MsgNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{5}
}

func (m *MsgNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotify.Unmarshal(m, b)
}
func (m *MsgNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotify.Marshal(b, m, deterministic)
}
func (m *MsgNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotify.Merge(m, src)
}
func (m *MsgNotify) XXX_Size() int {
	return xxx_messageInfo_MsgNotify.Size(m)
}
func (m *MsgNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotify proto.InternalMessageInfo

type MsgNotifyUser struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNotifyUser) Reset()         { *m = MsgNotifyUser{} }
func (m *MsgNotifyUser) String() string { return proto.CompactTextString(m) }
func (*MsgNotifyUser) ProtoMessage()    {}
func (*MsgNotifyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{6}
}

func (m *MsgNotifyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotifyUser.Unmarshal(m, b)
}
func (m *MsgNotifyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotifyUser.Marshal(b, m, deterministic)
}
func (m *MsgNotifyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotifyUser.Merge(m, src)
}
func (m *MsgNotifyUser) XXX_Size() int {
	return xxx_messageInfo_MsgNotifyUser.Size(m)
}
func (m *MsgNotifyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotifyUser.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotifyUser proto.InternalMessageInfo

type CommReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommReply) Reset()         { *m = CommReply{} }
func (m *CommReply) String() string { return proto.CompactTextString(m) }
func (*CommReply) ProtoMessage()    {}
func (*CommReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{7}
}

func (m *CommReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommReply.Unmarshal(m, b)
}
func (m *CommReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommReply.Marshal(b, m, deterministic)
}
func (m *CommReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommReply.Merge(m, src)
}
func (m *CommReply) XXX_Size() int {
	return xxx_messageInfo_CommReply.Size(m)
}
func (m *CommReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GwError)(nil), "iproto.GwError")
	proto.RegisterType((*Method1Request)(nil), "iproto.Method1Request")
	proto.RegisterType((*Method1Reply)(nil), "iproto.Method1Reply")
	proto.RegisterType((*Method2Request)(nil), "iproto.Method2Request")
	proto.RegisterType((*Method2Reply)(nil), "iproto.Method2Reply")
	proto.RegisterType((*MsgNotify)(nil), "iproto.MsgNotify")
	proto.RegisterType((*MsgNotifyUser)(nil), "iproto.MsgNotifyUser")
	proto.RegisterType((*CommReply)(nil), "iproto.CommReply")
}

func init() { proto.RegisterFile("tcpgate.proto", fileDescriptor_83d30d5155d328cc) }

var fileDescriptor_83d30d5155d328cc = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xfd, 0x86, 0x7c, 0xa1, 0xe1, 0x22, 0x28, 0xe3, 0x4f, 0x90, 0xb8, 0x20, 0xb3, 0x22, 0x2c,
	0x5a, 0x19, 0x17, 0x1a, 0x96, 0xa8, 0x61, 0x85, 0x31, 0x8d, 0xc6, 0xf5, 0x58, 0xc6, 0xb1, 0x09,
	0xed, 0x2d, 0x9d, 0xd1, 0xa6, 0x2e, 0x7d, 0x05, 0xdf, 0xc0, 0x67, 0xf0, 0x4d, 0x7c, 0x05, 0x1f,
	0xc4, 0xd0, 0x42, 0x89, 0x56, 0x5d, 0xcd, 0xb9, 0xe7, 0x9e, 0x7b, 0xee, 0x3d, 0x03, 0x0d, 0xe3,
	0x45, 0x4a, 0x18, 0x69, 0x47, 0x31, 0x1a, 0xa4, 0x55, 0x3f, 0x7b, 0x3b, 0x07, 0x0a, 0x51, 0xcd,
	0xa4, 0x23, 0x22, 0xdf, 0x11, 0x61, 0x88, 0x46, 0x18, 0x1f, 0x43, 0x9d, 0xab, 0xd8, 0x31, 0x58,
	0xe3, 0xe4, 0x3c, 0x8e, 0x31, 0xa6, 0x14, 0xfe, 0x7b, 0x38, 0x95, 0x6d, 0xd2, 0x25, 0xbd, 0x86,
	0x9b, 0x61, 0xda, 0x06, 0x2b, 0x90, 0x5a, 0x0b, 0x25, 0xdb, 0x95, 0x2e, 0xe9, 0xd5, 0xdc, 0x55,
	0xc9, 0xb6, 0xa0, 0x39, 0x91, 0xe6, 0x1e, 0xa7, 0x03, 0x57, 0xce, 0x1f, 0xa4, 0x36, 0xac, 0x09,
	0x1b, 0x05, 0x13, 0xcd, 0xd2, 0xb5, 0x82, 0x97, 0x14, 0x3c, 0x57, 0xd4, 0xa1, 0x36, 0xd1, 0xea,
	0x02, 0x8d, 0x7f, 0x97, 0xb2, 0x4d, 0x68, 0x14, 0xc5, 0xb5, 0x96, 0xf1, 0xa2, 0x7b, 0x8a, 0x41,
	0x90, 0x49, 0xf9, 0x1b, 0x01, 0xb8, 0xf2, 0xa2, 0xb1, 0x30, 0x32, 0x11, 0x29, 0x75, 0xc1, 0x5a,
	0xee, 0xa2, 0x7b, 0x76, 0x1e, 0xd4, 0xfe, 0x7a, 0x4e, 0x67, 0xa7, 0xc4, 0x2f, 0x56, 0xee, 0x3f,
	0xbf, 0x7f, 0xbc, 0x54, 0xb6, 0x59, 0xd3, 0x79, 0x1c, 0x38, 0x2a, 0x71, 0x82, 0xbc, 0x39, 0x24,
	0xfd, 0xb5, 0x27, 0xff, 0xee, 0xc9, 0x7f, 0xf1, 0xe4, 0x7f, 0x79, 0xf2, 0x21, 0xe9, 0xf3, 0x14,
	0xea, 0xcb, 0xab, 0xcf, 0x30, 0x09, 0xe9, 0x21, 0x54, 0xf3, 0x80, 0xb4, 0x55, 0x38, 0xad, 0x32,
	0x77, 0x0a, 0xaa, 0x48, 0xcd, 0xfe, 0xd1, 0x13, 0x80, 0xf5, 0x97, 0xd0, 0xdd, 0xd2, 0xd4, 0x82,
	0xfe, 0x71, 0x72, 0xd4, 0x83, 0x96, 0x87, 0x81, 0xfd, 0x34, 0x0f, 0xa5, 0xb1, 0xc7, 0x37, 0x99,
	0x60, 0x64, 0x2d, 0xc1, 0x25, 0x79, 0xad, 0xac, 0xf0, 0x6d, 0x35, 0x7b, 0x8e, 0x3e, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x80, 0x4c, 0xa4, 0x5a, 0x41, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TcpGatewayClient is the client API for TcpGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TcpGatewayClient interface {
	// 后端服务1
	// 注释
	// @transmit
	// @target backendsvr1 后端目标服务名
	// @id 2 对应请求协议的id
	Method1(ctx context.Context, in *Method1Request, opts ...grpc.CallOption) (*Method1Reply, error)
	// 后端服务2
	// 注释
	// @transmit
	// @target backendsvr2 后端目标服务名
	// @id 3 对应请求协议的id
	Method2(ctx context.Context, in *Method2Request, opts ...grpc.CallOption) (*Method2Reply, error)
}

type tcpGatewayClient struct {
	cc *grpc.ClientConn
}

func NewTcpGatewayClient(cc *grpc.ClientConn) TcpGatewayClient {
	return &tcpGatewayClient{cc}
}

func (c *tcpGatewayClient) Method1(ctx context.Context, in *Method1Request, opts ...grpc.CallOption) (*Method1Reply, error) {
	out := new(Method1Reply)
	err := c.cc.Invoke(ctx, "/iproto.TcpGateway/Method1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tcpGatewayClient) Method2(ctx context.Context, in *Method2Request, opts ...grpc.CallOption) (*Method2Reply, error) {
	out := new(Method2Reply)
	err := c.cc.Invoke(ctx, "/iproto.TcpGateway/Method2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcpGatewayServer is the server API for TcpGateway service.
type TcpGatewayServer interface {
	// 后端服务1
	// 注释
	// @transmit
	// @target backendsvr1 后端目标服务名
	// @id 2 对应请求协议的id
	Method1(context.Context, *Method1Request) (*Method1Reply, error)
	// 后端服务2
	// 注释
	// @transmit
	// @target backendsvr2 后端目标服务名
	// @id 3 对应请求协议的id
	Method2(context.Context, *Method2Request) (*Method2Reply, error)
}

// UnimplementedTcpGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedTcpGatewayServer struct {
}

func (*UnimplementedTcpGatewayServer) Method1(ctx context.Context, req *Method1Request) (*Method1Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Method1 not implemented")
}
func (*UnimplementedTcpGatewayServer) Method2(ctx context.Context, req *Method2Request) (*Method2Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Method2 not implemented")
}

func RegisterTcpGatewayServer(s *grpc.Server, srv TcpGatewayServer) {
	s.RegisterService(&_TcpGateway_serviceDesc, srv)
}

func _TcpGateway_Method1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Method1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpGatewayServer).Method1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iproto.TcpGateway/Method1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpGatewayServer).Method1(ctx, req.(*Method1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TcpGateway_Method2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Method2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpGatewayServer).Method2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iproto.TcpGateway/Method2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpGatewayServer).Method2(ctx, req.(*Method2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _TcpGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iproto.TcpGateway",
	HandlerType: (*TcpGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Method1",
			Handler:    _TcpGateway_Method1_Handler,
		},
		{
			MethodName: "Method2",
			Handler:    _TcpGateway_Method2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcpgate.proto",
}

// TcpGateDownClient is the client API for TcpGateDown service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TcpGateDownClient interface {
	// 广播通知
	Notify(ctx context.Context, in *MsgNotify, opts ...grpc.CallOption) (*CommReply, error)
	NotifyUser(ctx context.Context, in *MsgNotifyUser, opts ...grpc.CallOption) (*CommReply, error)
}

type tcpGateDownClient struct {
	cc *grpc.ClientConn
}

func NewTcpGateDownClient(cc *grpc.ClientConn) TcpGateDownClient {
	return &tcpGateDownClient{cc}
}

func (c *tcpGateDownClient) Notify(ctx context.Context, in *MsgNotify, opts ...grpc.CallOption) (*CommReply, error) {
	out := new(CommReply)
	err := c.cc.Invoke(ctx, "/iproto.TcpGateDown/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tcpGateDownClient) NotifyUser(ctx context.Context, in *MsgNotifyUser, opts ...grpc.CallOption) (*CommReply, error) {
	out := new(CommReply)
	err := c.cc.Invoke(ctx, "/iproto.TcpGateDown/NotifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcpGateDownServer is the server API for TcpGateDown service.
type TcpGateDownServer interface {
	// 广播通知
	Notify(context.Context, *MsgNotify) (*CommReply, error)
	NotifyUser(context.Context, *MsgNotifyUser) (*CommReply, error)
}

// UnimplementedTcpGateDownServer can be embedded to have forward compatible implementations.
type UnimplementedTcpGateDownServer struct {
}

func (*UnimplementedTcpGateDownServer) Notify(ctx context.Context, req *MsgNotify) (*CommReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (*UnimplementedTcpGateDownServer) NotifyUser(ctx context.Context, req *MsgNotifyUser) (*CommReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyUser not implemented")
}

func RegisterTcpGateDownServer(s *grpc.Server, srv TcpGateDownServer) {
	s.RegisterService(&_TcpGateDown_serviceDesc, srv)
}

func _TcpGateDown_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpGateDownServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iproto.TcpGateDown/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpGateDownServer).Notify(ctx, req.(*MsgNotify))
	}
	return interceptor(ctx, in, info, handler)
}

func _TcpGateDown_NotifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNotifyUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpGateDownServer).NotifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iproto.TcpGateDown/NotifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpGateDownServer).NotifyUser(ctx, req.(*MsgNotifyUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _TcpGateDown_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iproto.TcpGateDown",
	HandlerType: (*TcpGateDownServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _TcpGateDown_Notify_Handler,
		},
		{
			MethodName: "NotifyUser",
			Handler:    _TcpGateDown_NotifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcpgate.proto",
}
