name: GrpcTcpGate
ver: 1.0.0
loglevel: 7
pprof: 9697
consul:
  address: http://127.0.0.1:8500
  token:
  healthtype: http
  healthport: 30100
endpoint:
  backendsvr1:
    name: backendsvr1
    address: consul:///backendsvr1
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
  backendsvr2:
    name: backendsvr2
    address: consul:///backendsvr2
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
  backendsvr3:
    name: backendsvr3
    address: consul:///backendsvr3
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
servelist:
  - name: gate_tcp
    type: tcp # 0:http 1:tcp 2:ws
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
    buffersize: 30000
    maxconn: 10000
    idletimeout: 90s
    sendchansize: 1024
    recvchansize: 1024
    port: 10001
  - name: gate_ws
    type: ws # 0:http 1:tcp 2:ws
    secure: false
    certfiles:
      - cert: cert.pem
        priv: priv.key
        ca: ca.pem
    buffersize: 30000
    maxconn: 10000
    idletimeout: 90s
    sendchansize: 1024
    recvchansize: 1024
    port: 10002
